# +------------------------------------------------------------+ #
# Item2Chat Configuration
# +------------------------------------------------------------+ #

# NOTE: Do NOT put tabs anywhere in the config!

Messages:
  ErrorMsg : "&c[Item2Chat] : Some error occured."
  NoItem: "&c[Item2Chat] : You must have something in your hand to use Item2Chat!"
  NoPermission: "&c[Item2Chat] : You don't have a permission."
  CoolDown: "&c[Item2Chat] You have to wait for &b%remaining% &aseconds."
  LetsOpenSnapshot: "&a[Item2Chat] Let's open %player%'s inventory snapshot!."
  SnapshotExpired: "&c[Item2Chat] %player%'s inventory snapshot has expired!"


HelpMessages:
  banner:
    msg: "=== &e[&aItem2Chat Commands List (%version%)&e] &r==="  
  help:
    msg: "&a/item2chat help : displays this help menu."
  reload:
    msg: "&a/item2chat reload : reloads config file."
    permission: "item2chat.reload"
  debug:
    msg: "&a/item2chat debug <true|false> : turn on / off the debug mode."
    permission: "item2chat.debug"

#if this option is true, the plguin will try to send the chat packet in asynchronous fashion
AsynchronousMode: false

# if you encounter any issue with your chat plugin, try adjusting this option.
# adjust these event priority if those event processes from this plugin
# interfere with other plugins' event processes.
EventPriorityMap:
  AsyncPlayerChatEvent: "LOWEST"
  PlayerCommandPreprocessEvent: "LOWEST"

Cooldown: 0  # in seconds
CaseSensitive: false
ItemKeyword:
  - "[item]"
  - "{item}"
  - "{i}"

InlineFormat: "&r%name%%INLINE_AMOUNT%&r"
InlineAmountFormat: " &7&o(x%amount%)"

# if inventory keyword is used, the inventory snapshot will be kept for the
# following duration (in ticks)
RetainSnapshot: 300 # in ticks

# to use the below feature, you need OpenInv plugin installed on your server.
InvTitle: "%player_name%'s inventory"
InvInline: "%player_name%'s inventory"
InvKeyword:
  - "[inventory]"
  - "{inventory}"
  - "[inv]"
  - "{inv}"
  - "[brag]"
  - "{brag}"

