on chat:
	event is not canceled
	set {_message} to message
	set {_color} to {chatcolor::%player's uuid%} ? "&7"
	set {_message} to emojify({_message}) if player has permission "perks.emoji"
	set {_suffix} to " &8[%{suffix::%player's uuid%}%&8]" if {suffix::%player's uuid%} is set
	set chat format to "&7[%{prestige::%player's uuid%} ? 0%] &7%player's prefix%%player%%{_suffix} ? """"%&7: %{_color}%%{_message}%"
