function getTag(t: item, e: text) :: number:
	return (tag {_e} of nbt of {_t}) ? 0

function getPickaxeEnchants(t: item) :: objects:
	add (getTag({_t}, "efficiency") and "Efficiency") to {_e::*}
	add (getTag({_t}, "fortune") and "Fortune") to {_e::*}
	add (getTag({_t}, "jump") and "Jump") to {_e::*}
	add (getTag({_t}, "flight") and "Flight") to {_e::*}
	add (getTag({_t}, "keyfinder") and "Keyfinder") to {_e::*}
	add (getTag({_t}, "explosive") and "Explosive") to {_e::*}
	add (getTag({_t}, "jackhammer") and "Jackhammer") to {_e::*}
	add (getTag({_t}, "slice") and "Slice") to {_e::*}
	add (getTag({_t}, "layer") and "Layer") to {_e::*}
	add (getTag({_t}, "laser") and "Laser") to {_e::*}
	add (getTag({_t}, "cube") and "Cube") to {_e::*}
	add (getTag({_t}, "xpfinder") and "Xpfinder") to {_e::*}
	add (getTag({_t}, "chunk") and "Chunk") to {_e::*}
	add (getTag({_t}, "tsunami") and "Tsunami") to {_e::*}
	return {_e::*}

function updatePickaxeLevel(t: item) :: item:
	set line 1 of {_t}'s lore to ""
	set line 2 of {_t}'s lore to "<##f2b84b>&l| &7Level: &f%insertComma(getTag({_t}, ""level""))%"
	set line 3 of {_t}'s lore to "<##f2b84b>&l| &7Points: &f%insertComma(getTag({_t}, ""points""))%"
	set {_progress} to round (((getTag({_t}, "xp"))/(getTag({_t}, "xpn"))) * 100)
	set line 4 of {_t}'s lore to "<##f2b84b>&l| &7Progress: &f%{_progress}%%%"
	set line 5 of {_t}'s lore to ""
	return {_t}

function updatePickaxe(t: item) :: item:
	updateScoreboard({_p})
	set {_t} to updatePickaxeLevel({_t})
	set {_enchs::*} to getPickaxeEnchants({_t})
	loop ((size of {_enchs::*})/2) times:
		set {_level} to {_enchs::%loop-value * 2 - 1%}
		set {_enchant} to {_enchs::%loop-value * 2%}
		set line (loop-value + 5) of {_t}'s lore to "&8&l| &7%{_enchant}%&7 %insertComma({_level})%"
	enchant {_t} with "efficiency %getTag({_t}, ""efficiency"")%" parsed as a enchantment type
	return {_t}

function upgradePickaxe(p: player, t: item, e: text, l: number, m: number, gct: text):
	set {_u} to {_p}'s uuid
	if {_gct} contains "middle":
		close {_p}'s inventory
		set metadata "thread" of {_p} to true
		while 1 = 1:
			if ({_u} parsed as a offline player) is online:
				set {_l} to getTag({_p}'s tool, {_e})
				set {_pr} to enchantPrice({_e}, {_l})
				if {balance::%{_u}%} >= {_pr}:
					if {_l} < {_m}:
						add "{%{_e}%:%getTag({_t}, {_e})+1%}" to nbt of {_t}
						remove {_pr} from {balance::%{_u}%}
						playSound({_p}, "ENTITY_VILLAGER_YES")
						send "<##4b8bf2>&lENCHANT &7Purchased <##81aef7>%{_e}%&7 for <##81aef7>$%formatNumber({_pr})%&7." to {_p}
						set {_p}'s tool to updatePickaxe({_t})
						updateScoreboard({_p})
						wait 1 tick
					else:
						playSound({_p}, "ENTITY_VILLAGER_NO")
						send "&cYou already maxed this enchant." to {_p}
						exit loop
				else:
					playSound({_p}, "ENTITY_VILLAGER_NO")
					send "&cYou need $%formatNumber({_pr} - {balance::%{_u}%})%&c more to buy this!" to {_p}
					exit loop
			else:
				exit loop
		delete metadata "thread" of {_p}
	else:
		set {_pr} to enchantPrice({_e}, {_l})
		if {balance::%{_u}%} >= {_pr}:
			if {_l} < {_m}:
				add "{%{_e}%:%getTag({_t}, {_e})+1%}" to nbt of {_t}
				remove {_pr} from {balance::%{_u}%}
				playSound({_p}, "ENTITY_VILLAGER_YES")
				send "<##4b8bf2>&lENCHANT &7Purchased <##81aef7>%{_e}%&7 for <##81aef7>$%formatNumber({_pr})%&7." to {_p}
				set {_p}'s tool to updatePickaxe({_t})
				updateScoreboard({_p})
			else:
				playSound({_p}, "ENTITY_VILLAGER_NO")
				send "&cYou already maxed this enchant." to {_p}
		else:
			playSound({_p}, "ENTITY_VILLAGER_NO")
			send "&cYou need $%formatNumber({_pr} - {balance::%{_u}%})%&c more to buy this!" to {_p}
		pickaxeInv({_p})

function displayPickaxeInv(p: player):
	open virtual chest with 6 rows named "<##4b8bf2>&lUPGRADE PICKAXE" to {_p}
	fillSlots({_p}, 6)
	playSound({_p}, "ENTITY_BAT_TAKEOFF")
	pickaxeInv({_p})

function enchantPrice(e: text, l: number) :: number:
	return ({_l}*5000)^(1.14)+20000 if {_e} is "efficiency"
	return ({_l}*12500)^(1.17)+25000 if {_e} is "fortune"
	return 10000000 if {_e} is "jump"
	return 50000000 if {_e} is "flight"
	return ({_l}*100000)^(1.155)+400000 if {_e} is "keyfinder"
	return ({_l}*150000)^(1.15)+600000 if {_e} is "explosive"
	return ({_l}*125000)^(1.14)+550000 if {_e} is "jackhammer"
	return ({_l}*125000)^(1.14)+550000 if {_e} is "slice"
	return ({_l}*125000)^(1.15)+600000 if {_e} is "layer"
	return ({_l}*125000)^(1.14)+550000 if {_e} is "laser"
	return ({_l}*125000)^(1.15)+600000 if {_e} is "cube"
	return ({_l}*150000)^(1.16)+250000 if {_e} is "xpfinder"
	return ({_l}*175000)^(1.16)+750000 if {_e} is "chunk"
	return ({_l}*250000)^(1.17)+1000000 if {_e} is "tsunami"
	return 0

function enchantMax(e: text) :: number:
	return 500 if {_e} is "efficiency"
	return 1000000 if {_e} is "fortune"
	return 1 if {_e} is "jump"
	return 1 if {_e} is "flight"
	return 5000 if {_e} is "keyfinder"
	return 500 if {_e} is "explosive"
	return 1000 if {_e} is "jackhammer"
	return 1000 if {_e} is "slice"
	return 500 if {_e} is "layer"
	return 500 if {_e} is "laser"
	return 500 if {_e} is "cube"
	return 250 if {_e} is "xpfinder"
	return 5000 if {_e} is "chunk"
	return 10000 if {_e} is "tsunami"
	return 0

function enchantChance(e: text) :: number:
	return 4000 if {_e} is "jackhammer"
	return 4000 if {_e} is "slice"
	return 4000 if {_e} is "laser"
	return 5000 if {_e} is "layer"
	return 6000 if {_e} is "cube"
	return 250000 if {_e} is "xpfinder"
	return 8250 if {_e} is "explosive"
	return 25000000 if {_e} is "chunk"
	return 100000000 if {_e} is "tsunami"
	return 0

function enchantDescription(e: text) :: text:
	return "Makes you mine faster" if {_e} is "efficiency"
	return "Makes you more money" if {_e} is "fortune"
	return "Makes you jump higher" if {_e} is "jump"
	return "Allows you to fly" if {_e} is "flight"
	return "Chance to find a key" if {_e} is "keyfinder"
	return "Chance to explode" if {_e} is "explosive"
	return "5x5 Horizontal" if {_e} is "jackhammer"
	return "5x5 Verticle" if {_e} is "slice"
	return "Makes the entire layer" if {_e} is "layer"
	return "Makes a cross in the mine" if {_e} is "laser"
	return "Makes 3x3x3 cube" if {_e} is "cube"
	return "Chance to find more XP" if {_e} is "xpfinder"
	return "Mines an entire chunk" if {_e} is "chunk"
	return "Chance to explode the entire mine" if {_e} is "tsunami"
	return ""

function guiPickaxeItem(p: player, slot: number, item: item, enchant: text):
	set {_tool} to {_p}'s tool
	set {_level} to getTag({_tool}, {_enchant})
	set {_max} to enchantMax({_enchant})

	set {_item} to {_item} named "<##81aef7>%{_enchant} in proper case% &7(%insertComma({_level})%/%insertComma({_max})%)" with lore "" and "&7Price: <##81aef7>$%formatNumber(enchantPrice({_enchant}, {_level}))%" and "" and "<##81aef7>Click &7to buy one." and "<##81aef7>MMB &7to buy as many as possible."
	set line 6 of lore of {_item} to ""
	set line 7 of lore of {_item} to "&7&o(( %enchantDescription({_enchant})% ))"
	if enchantChance({_enchant}) is not 0:
		set {_chance} to (({_level}/(enchantChance({_enchant}))) * 100)
		set line 8 of lore of {_item} to "&7&o(( Chance: %{_chance}%%% ))"
	format gui slot {_slot} of {_p} with {_item} to run:
		upgradePickaxe({_p}, {_tool}, {_enchant}, {_level}, {_max}, "%gui-click-type%")

function pickaxeInv(p: player):
	set {_u} to {_p}'s uuid
	set {_t} to {_p}'s tool

	format gui slot 12 of {_p} with {_p}'s skull
	format gui slot 14 of {_p} with {_t}

	guiPickaxeItem({_p}, 28, hopper, "jackhammer")
	guiPickaxeItem({_p}, 29, iron sword, "slice")
	guiPickaxeItem({_p}, 30, emerald, "fortune")
	guiPickaxeItem({_p}, 31, tnt, "explosive")
	guiPickaxeItem({_p}, 32, arrow, "efficiency")
	guiPickaxeItem({_p}, 33, feather, "flight")
	guiPickaxeItem({_p}, 34, rabbit foot, "jump")
	guiPickaxeItem({_p}, 37, anvil, "chunk")
	guiPickaxeItem({_p}, 38, water bucket, "tsunami")
	guiPickaxeItem({_p}, 39, lectern, "keyfinder")
	guiPickaxeItem({_p}, 40, red carpet, "layer")
	guiPickaxeItem({_p}, 41, redstone torch, "laser")
	guiPickaxeItem({_p}, 42, stone, "cube")
	guiPickaxeItem({_p}, 43, xp bottle, "xpfinder")

on right click:
	player's tool is pickaxe
	metadata "thread" of player is not set
	displayPickaxeInv(player)

on join:
	set player's flight mode to false if player is not op
	remove jump boost from player

on hotbar switch:
	cancel event if metadata "thread" of player is true
	apply jump boost of tier 2 without any particles to player for 999 days if getTag(player's tool, "jump") > 0
	set player's flight mode to true if getTag(player's tool, "flight") > 0

on inventory open:
	metadata "thread" of player is true
	wait 1 tick
	close player's inventory