function getPrice(b: block) :: number:
	return 500 if {_b} is white terracotta
	return 0

function blockValidator(b: block) :: boolean:
	if {_b} is not air:
		if "%region at {_b}%" contains "mine":
			return true
	return false

function simMine(p: player, t: number):
	set {_u} to {_p}'s uuid
	add {_t} to {balance::%{_u}%}
	add 1 to {xp::%{_u}%}
	add 1 to {mined::%{_u}%}

function updateLevel(p: player):
	set {_u} to {_p}'s uuid
	while {xp::%{_u}%} >= ({xpn::%{_u}%} ? 100):
		add 1 to {level::%{_u}%}
		remove ({xpn::%{_u}%} ? 100) from {xp::%{_u}%}
		set {xpn::%{_u}%} to round ({xpn::%{_u}%} ? 100)^1.005
		send "&f&lLEVEL &7Leveled up to level &f%{level::%{_u}%}%&7." to {_p}
		wait 1 tick

on break:
	player's tool is pickaxe
	clear drops

	set metadata "nuker" of player to metadata "nuker" of player + 1
	if metadata "nuker_yes" of player is not set:
		set metadata "nuker_yes" of player to true
		wait 5 seconds
		if metadata "nuker" of player > 150:
			send "&7&lANTICHEAT &8| &" to all players where [input has permission "staff"]
		if metadata "nuker" of player > 350:
			send "you wouldve gotten banned"
		delete metadata "nuker" of player
		delete metadata "nuker_yes" of player

	add 1 to {mined::%player's uuid%}
	set {_price} to getPrice(event-block)
	set {_fort} to random integer between 1 and (getTag(player's tool, "fortune") + 1)
	set {_total} to {_price} * {_fort}
	add {_total} to {balance::%player's uuid%}
	add 1 to {xp::%player's uuid%}

	set {_loc} to event-block's location
	set {_x} to x-loc of event-block
	set {_y} to y-loc of event-block
	set {_z} to z-loc of event-block

	if (random integer between 1 and 3000) <= getTag(player's tool, "jackhammer"):
		set {_loc1} to location({_x} - 2, {_y}, {_z} - 2)
		set {_loc2} to location({_x} + 2, {_y}, {_z} + 2)
		loop all blocks within {_loc1} and {_loc2}:
			if blockValidator(loop-block) is true:
				simMine(player, {_total})
				set loop-block to air

	if (random integer between 1 and 7250) <= getTag(player's tool, "explosive"):
		loop all blocks in radius 3 around event-block:
			if blockValidator(loop-block) is true:
				simMine(player, {_total})
				set loop-block to air

	if (random integer between 1 and 25000000) <= getTag(player's tool, "chunk"):
		loop all blocks within chunk at event-block:
			if blockValidator(loop-block) is true:
				simMine(player, {_total})
				set loop-block to air

	if (random integer between 1 and 100000000) <= getTag(player's tool, "tsunami"):
		loop all blocks in radius 40 around event-block:
			if blockValidator(loop-block) is true:
				simMine(player, {_total})
				set loop-block to air

	updateLevel(player)
	updateScoreboard(player)
