Punishments:
  broadcast_on_punishment: false
  max_wave_size: 100
Logs:
  log_file: true
Notifications:
  awareness_notifications: true
  individual_only_notifications: false
  enable_notifications_on_login: true
  send_silent_notifications: true
  send_uncertain_notifications: true
Protections:
  explosion_detection_cooldown: 4
  reconnect_cooldown: 1
  use_tps_protection: true
  max_supported_player_latency: 500
  use_teleport_protection: false
  avoid_self_bow_damage: true
  player_limit_per_ip: 0
  interactions_per_tick: 10
  disallowed_building: true
  custom_knockback: false
  limit_server_flying: false
Important:
  op_bypass: false
  enable_permissions: true
  use_permission_cache: false
  server_version: Configure this if the plugin is unable to detect your server's version.
  violations_reset_seconds: 60
  violations_reset_on_kick: false
  cloud_feature: true
Detections:
  ground_teleport_on_detection: true
  fall_damage_on_teleport: false
  allow_cancelled_hit_checking: false
  update_blocks_upon_violation: false
  ignore_shields: false
Performance:
  enable_false_positive_detection: false
